# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vcom -work work +acc C:/Work/fir_filter_system/packages/fir_fixed_generics_package.vhdl C:/Work/fir_filter_system/packages/fixed_to_signed_package.vhdl C:/Work/fir_filter_system/rtl/fir_filter_fixed.vhdl
vsim  -onfinish exit -t 1ps -foreign "cocotb_init C:/Python312/Lib/site-packages/cocotb/libs/cocotbfli_modelsim.dll"   sim_build/work.fir_filter_fixed
onbreak resume
run -all
quit
