function Hd = filter
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 22-Aug-2024 16:53:01

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are normalized to 1.

N  = 50;         % Order
Fc = 0.25;       % Cutoff Frequency
TM = 'Rolloff';  % Transition Mode
R  = 0.5;        % Rolloff
DT = 'sqrt';     % Design Type

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc, R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
