function y = untitled(x)
%UNTITLED Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 22-Aug-2024 17:41:18

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Raised-cosine filter designed using the FIRRCOS function.
    %
    % % All frequency values are normalized to 1.
    %
    % N  = 50;         % Order
    % Fc = 0.2;        % Cutoff Frequency
    % TM = 'Rolloff';  % Transition Mode
    % R  = 0.5;        % Rolloff
    % DT = 'sqrt';     % Design Type
    %
    % % Create the window vector for the design algorithm.
    % win = hamming(N+1);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = firrcos(N, Fc, R, 2, TM, DT, [], win);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-1.02888044019e-05 8.29240421830918e-05 ...
        0.00012410155047817 4.53101869356487e-05 -0.000156507007966506 ...
        -0.000339231804032608 -0.000251199042933597 0.000241443415308379 ...
        0.000883935411061879 0.0010500614964844 0.000241219586585537 ...
        -0.00121647765841029 -0.00198799908676725 -0.00061311866946171 ...
        0.0028574854489321 0.00579025050989564 0.00393216079698919 ...
        -0.00533959689559654 -0.0192322326123931 -0.0282204886459442 ...
        -0.0193563778628905 0.0165191226743058 0.0775321346567606 ...
        0.148389791936159 0.205445310864865 0.227323954473516 0.205445310864865 ...
        0.148389791936159 0.0775321346567606 0.0165191226743058 ...
        -0.0193563778628905 -0.0282204886459442 -0.0192322326123931 ...
        -0.00533959689559654 0.00393216079698919 0.00579025050989564 ...
        0.0028574854489321 -0.00061311866946171 -0.00198799908676725 ...
        -0.00121647765841029 0.000241219586585537 0.0010500614964844 ...
        0.000883935411061879 0.000241443415308379 -0.000251199042933597 ...
        -0.000339231804032608 -0.000156507007966506 4.53101869356487e-05 ...
        0.00012410155047817 8.29240421830918e-05 -1.02888044019e-05]);
end

y = step(Hd,double(x));


% [EOF]
